### ISSUE TITLE
Design the visualization for badge pathways 

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/badgeopolis#3]
As conceptualized in this post by @chloeatplay  http://chloeatplay.tumblr.com/post/55901798994/a-flaneurs-thoughts-on-openbadges-pathways - we need to prototype a way to visualize pathways.

Pathways are essentially roadmaps for a user to gain a skill or expertise. 

cc: @chloeatplay @carlacasilli

**Comment by chloeatplay** [comment]
Some Concept Sketches Below: More detailed expanation on my flickr page.http://www.flickr.com/photos/66772999@N05/
![pathways_sketches-03-02](https://f.cloud.github.com/assets/1945209/1026986/408a3540-0e68-11e3-9aad-b26fd23eecd4.png)
![pathways_sketches-03-01](https://f.cloud.github.com/assets/1945209/1026989/63995250-0e68-11e3-84c7-fcafcbe24941.png)
![pathways-05](https://f.cloud.github.com/assets/1945209/1026999/9cd232c6-0e68-11e3-869c-c46bb3541906.png)
![pathways_sketches-03](https://f.cloud.github.com/assets/1945209/1026984/38a736ca-0e68-11e3-9c79-e9bfdca28a60.png)
